# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "CI/CD"
on:
  push:
    branches: [ main, cypress ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Cypress run
       uses: cypress-io/github-action@v2
       with:
         start: docker-compose up -d
         wait-on: 'http://localhost:8080'
         wait-on-timeout: 900
